version: '3.8'
services:
  node:
    build: .
    ports:
      - "3006:3006"
    volumes:
      - .:/app/.
    runtime: nvidia
    command: "node server.js"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

